### ISSUE TITLE
Syntax highlighting problem when using Apostrophe in .conf files

### ISSUE THREAD

**Issue by hovu96** [splunk/vscode-extension-splunk#1]
This is an example .conf file created by Splunk:
![image](https://user-images.githubusercontent.com/870504/71715294-3d8a0a80-2e11-11ea-8eb5-e33910cc0a58.png)

Attribute values containing an apostrophe breaks syntax highlighting. A workaround is quoting the value.

**Comment by JasonConger** [comment]
I am unable to reproduce this issue.  Was there a particular .conf file you were editing?

**Comment by hovu96** [comment]
It turned out this was caused by #3
