### ISSUE TITLE
Linting issue with stanza & searches

### ISSUE THREAD

**Issue by Jalkar** [splunk/vscode-extension-splunk#12]
The linter detect invalid key for stanza like savedsearches or macro when there is multi line searches included : 
![image](https://user-images.githubusercontent.com/5929339/75545690-479e4300-5a27-11ea-9ad9-e23daba52e61.png)

`Invalid key in stanza [my_saved_searches] in savedsearches.conf, line 41: earliest= @mon \.`

**Comment by JasonConger** [comment]
Adding a space at the beginning of the line for your additional lines should resolved this.  For example:

    [my_search]
    search = index=main \
     earliest = @mon \
     latest = @d \

**Comment by Jalkar** [comment]
yes but those are GUI edited file, I will not re-edit all my file for a faulty linter...

**Comment by JasonConger** [comment]
Fair enough.  We'll get this addressed.  Thanks for the use and feedback!

**Comment by JasonConger** [comment]
Version 0.2.3 addresses the multi-line issue.

**Comment by arcsector** [comment]
I think this should still be open - though this isn't throwing an error anymore, the syntax highlighting still identifies multi-line strings as multiple single-line strings, and doesn't respect the final backspace before the line terminator and newline.
