### ISSUE TITLE
Invalid key in stanza [eventtype=eventtype] in tags.conf

### ISSUE THREAD

**Issue by diogofgm** [splunk/vscode-extension-splunk#24]
The attributes of [eventtype=eventtype] stanza in tags.conf are marked by the extension as invalid (e.g. authentication = enabled)

**Comment by JasonConger** [comment]
Resolved in version 0.2.4

**Comment by diogofgm** [comment]
![Screenshot 2020-07-27 at 12 18 45](https://user-images.githubusercontent.com/4519265/88536224-54898780-d003-11ea-8957-020367756984.png)
The stanzas are recognized but the attributes still marked as invalid.
