### ISSUE TITLE
Compatibility with Windows WSL

### ISSUE THREAD

**Issue by sylbae** [splunk/vscode-extension-splunk#3]
Hello,

I am using Windows + WSL for Splunk development
Therefore I am using VS Code with WSL-mode to directly edit my Splunk files.

I tried to install your new extension... I can see basic features work (syntax highlighting) but I am being prompt to install missing extensions (not all extensions are installed by default when VS Code is working in WSL "remote" mode):

1. First I have been asked to enable Python extension --> ok no problem for this one
2. But now I am asked to enable the "Remote - SSH" extension. And I cannot do that, likely because I am running in WSL mode.

The exact error message is:
```
Cannot active the 'Splunk Extension' extension because it depends on the 'Remote - SSH' extension which is not loaded. Would you like to reload the window to load the extension?
```
I tried already reload as suggested but it does not work.

**Comment by JasonConger** [comment]
Thanks for the feedback.  In the meantime, you can remove the Remote SSH dependency by editing the package.json file located in your [extension directory ](https://code.visualstudio.com/docs/editor/extension-gallery#_where-are-extensions-installed).  Remove `ms-vscode-remote.remote-ssh` from the `extensionDependencies` section.  It should look like this:

    "extensionDependencies": [
            "ms-python.python"
        ],

**Comment by sylbae** [comment]
@JasonConger , Thanks a lot, it did solve the problem.
