### ISSUE TITLE
Adhoc search command not working because of typo

### ISSUE THREAD

**Issue by tstcw** [splunk/vscode-extension-splunk#30]
There is a typo  at 
https://github.com/splunk/vscode-extension-splunk/blob/ccb5f34bcb859af543abcb6eaaefc7c190bcbb5b/out/extension.js#L156
which prevents adhoc searches from working and the following error message to be thrown:

> The URL specified for the Splunk REST API is incorrect. Please check your settings.

Changing `splunk.commands.slkunkRestUrl` to `splunk.commands.splunkRestUrl` fixes the issue.

**Comment by JasonConger** [comment]
Resolved in version 0.2.4
