### ISSUE TITLE
Language is not compatible with existing splunk linter

### ISSUE THREAD

**Issue by arcsector** [splunk/vscode-extension-splunk#4]
# Summary
Langauge ID `splunk` is already taken by Chris' [`splunk-linter`](https://bitbucket.org/kristophbarbour/splunk-linter/src/master/) extension. The language ID in this overwrites the extension's language config, which is a shame because it has some really nice components to it.

## Proposed solution
Change language ID to `splunk_conf` to make sure it doesn't conflict.

**Comment by JasonConger** [comment]
Changes merged into feature branch https://github.com/splunk/vscode-extension-splunk/tree/arcsector-launguage-id for further testing.

**Comment by JasonConger** [comment]
Changes merged into feature branch https://github.com/splunk/vscode-extension-splunk/tree/arcsector-launguage-id for further testing.

**Comment by arcsector** [comment]
This has not been fixed and should not be closed.
