### ISSUE TITLE
Syntax highlighting for EXTRACT-<class> breaks when the class includes a comma

### ISSUE THREAD

**Issue by graememeyer** [splunk/vscode-extension-splunk#42]
![image](https://user-images.githubusercontent.com/3931530/116372515-5edfe880-a804-11eb-8674-3a1859d3fe63.png)

Commas are valid characters in the class name - you get them if you use the field extractor to extract multiple fields simultaneously from a single event. Probably just need a regex update. I wasn't able to discern where in the project such a highlight rule was. Happy to submit a PR if someone can point me to the relevant code.

**Comment by JasonConger** [comment]
Addressed in v0.2.8
