### ISSUE TITLE
Stanzas not supported for searchbnf.conf

### ISSUE THREAD

**Issue by bakermat** [splunk/vscode-extension-splunk#49]
When creating a custom search command in `searchbnf.conf` I get a `Stanza [mything-command] does not seem to be a valid stanza` error when adding a stanza.

Example:
```
[mything-command]
syntax = mything
```
A bare `syntax` command works, but whenever adding in a stanza it throws the error above. Tested on v0.28.

**Comment by JasonConger** [comment]
Addressed in v0.2.10
