### ISSUE TITLE
Attributes in modular inputs not recognized in inputs.conf

### ISSUE THREAD

**Issue by bakermat** [splunk/vscode-extension-splunk#50]
Inputs.conf with the following modular input will not recognize any attributes for that modular input. Tested on v0.28.
```
[my_modular_input]
python.version = python3
```

**Comment by dconnett-splunk** [comment]
I ran into this sam issue today as well. It looks like these fields are indeed in the inputs.conf.spec file. I am not sure how the code differentiates the different inputs.conf files, but I wonder if it's misidentifying the specific type of inputs.conf file:

https://github.com/splunk/vscode-extension-splunk/blob/master/spec_files/8.2/inputs.conf.spec

**Comment by JasonConger** [comment]
Addressed in v0.2.10
