### ISSUE TITLE
Debugging custom commands

### ISSUE THREAD

**Issue by jeoshiro** [splunk/vscode-extension-splunk#54]
Splunk Enterprise 8.2.0
Ubuntu 20.04.2 LTS
Extension version: 0.2.8

The python debugger in the Splunk Extension does not work when debugging a custom command (reporting command). It runs fine without the debugger, but when using the debugger it crashes at the dispatch() function and returns the following traceback:

Traceback (most recent call last):
  File "/opt/splunk/etc/apps/<app>/bin/<command>.py", line 149, in <module>
    dispatch(exportExcel, sys.argv, sys.stdin, sys.stdout, __name__)
  File "/opt/splunk/etc/apps/<app>/bin/../lib/splunklib/searchcommands/search_command.py", line 1144, in dispatch
    command_class().process(argv, input_file, output_file, allow_empty_input)
  File "/opt/splunk/etc/apps/<app>/bin/../lib/splunklib/searchcommands/search_command.py", line 450, in process
    self._process_protocol_v2(argv, ifile, ofile)
  File "/opt/splunk/etc/apps/<app>/bin/../lib/splunklib/searchcommands/search_command.py", line 788, in _process_protocol_v2
    self._record_writer.write_metadata(self._configuration)
  File "/opt/splunk/etc/apps/<app>/bin/../lib/splunklib/searchcommands/internals.py", line 813, in write_metadata
    self._write_chunk(metadata, '')
  File "/opt/splunk/etc/apps/<app>/bin/../lib/splunklib/searchcommands/internals.py", line 843, in _write_chunk
    self.write(start_line)
  File "/opt/splunk/etc/apps/<app>/bin/../lib/splunklib/searchcommands/internals.py", line 557, in write
    self.ofile.write(data)
  File "/opt/splunk/etc/apps/SA-VSCode/bin/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_io.py", line 40, in write
    r.write(s)
TypeError: write() argument must be str, not bytes

The custom running code is similar to the python examples in the SDK repo in: https://github.com/splunk/splunk-sdk-python/tree/master/examples/searchcommands_app/package/bin/

Tried to debug filter.py from the examples and returned the same error.

**Comment by JasonConger** [comment]
I've noticed an anomaly where adding the 4 debug import lines outside of the `class` can produce errors like these.  It seems to be an import collision, and I'm digging further.  In the meantime, try adding the imports closer to the code you want to debug.  For example, if you want to debug the following code:

```
@Configuration()
class GenerateTextCommand(GeneratingCommand):

    count = Option(require=True, validate=validators.Integer(0))
    text = Option(require=True)

    def generate(self):
        text = self.text
        self.logger.debug("Generating %d events with text %s" % (self.count, self.text))
        for i in range(1, self.count + 1):
            yield {'_serial': i, '_time': time.time(), '_raw': six.text_type(i) + '. ' + text}

dispatch(GenerateTextCommand, sys.argv, sys.stdin, sys.stdout, __name__)
```

Add the 4 debug lines in the `generate` method.  Something like this:

```
@Configuration()
class GenerateTextCommand(GeneratingCommand):

    count = Option(require=True, validate=validators.Integer(0))
    text = Option(require=True)

    def generate(self):
        import sys, os
        sys.path.append(os.path.join(os.environ['SPLUNK_HOME'],'etc','apps','SA-VSCode','bin'))
        import splunk_debug as dbg
        dbg.enable_debugging(timeout=25)
        text = self.text
        self.logger.debug("Generating %d events with text %s" % (self.count, self.text))
        for i in range(1, self.count + 1):
            yield {'_serial': i, '_time': time.time(), '_raw': six.text_type(i) + '. ' + text}

dispatch(GenerateTextCommand, sys.argv, sys.stdin, sys.stdout, __name__)
```

**Comment by cah-scott-smiesko** [comment]
Hi, was this bug fixed in a pull request later on?
