### ISSUE TITLE
Errors from "Dynamic Stanza" Names

### ISSUE THREAD

**Issue by tdshplunk** [splunk/vscode-extension-splunk#60]
For stanzas that can have non-static stanza names, the key names under the stanza's can't be found in the spec file. Screenshot for reference. This screenshot only shows the authentication.conf, but extends to more than just this file
<img width="872" alt="Screen Shot 2022-05-18 at 7 27 34 PM" src="https://user-images.githubusercontent.com/105827272/169172153-5ebc9853-0954-4737-82d7-e1ebbb45f432.png">

**Comment by JasonConger** [comment]
Addressed in v0.2.10
