### ISSUE TITLE
Unknown Key Errors under Stanzas

### ISSUE THREAD

**Issue by tdshplunk** [splunk/vscode-extension-splunk#61]
Similar to #60 authorize.conf has some issue that are harder to show in a screenshot. If required I can try to craft something to maintain privacy of the real data. Here are a list of properties that do work (with no errors):
- importRole
- srchFilter
- srchIndexesAllowed
- srchIndexesDefault

And don't work (meaning the extensions shows an error):
- accelerate_search
- change_own_password
- delete_messages
- edit_search_schedule_window
- get_metadata
- get_typeahead
- input_file
- reset_apps_view
- rest_properties-get
- rest_properties_set
- search

**Comment by JasonConger** [comment]
Addressed in version 0.2.10
