### ISSUE TITLE
Default Stanza Shows Error in distsearch.conf

### ISSUE THREAD

**Issue by tdshplunk** [splunk/vscode-extension-splunk#62]
The stanza for default errors.
<img width="499" alt="Screen Shot 2022-05-18 at 7 46 08 PM" src="https://user-images.githubusercontent.com/105827272/169173065-207c7528-af46-491b-aa0b-0f365ea7ff53.png">
)

**Comment by JasonConger** [comment]
Addressed in version 0.2.9
