### ISSUE TITLE
colud not enumerate saved searches. self signed certificate in certificate chain

### ISSUE THREAD

**Issue by mcauto** [splunk/vscode-extension-splunk#63]
I use self-signed certification.

How to skip verify ssl?

Splunk Enterprise 8.2.0
Ubuntu 20.04 on Windows (WSL2)
Extension version: 0.2.8

![image](https://user-images.githubusercontent.com/15080806/173513172-ce6b89a3-9555-425d-9e94-c9fa8356ffcc.png)

**Comment by JasonConger** [comment]
Addressed in version 0.2.9.  A new extension setting named `Enable Certificate Verification` has been added to enable/disable certificate verification.  https://github.com/splunk/vscode-extension-splunk/wiki/Extension-Settings#command-settings

**Comment by KbyteTutu** [comment]
> Addressed in version 0.2.10. A new extension setting named `Enable Certificate Verification` has been added to enable/disable certificate verification. https://github.com/splunk/vscode-extension-splunk/wiki/Extension-Settings#command-settings

seens it's not working properly. I unchecked that option but the software still warn me "Could not enumerate saved searches. self signed certificate in certificate chain"

**Comment by mcauto** [comment]
> Addressed in version 0.2.10. A new extension setting named `Enable Certificate Verification` has been added to enable/disable certificate verification. https://github.com/splunk/vscode-extension-splunk/wiki/Extension-Settings#command-settings

It's not working :(
