### ISSUE TITLE
ignore SSL feature not working

### ISSUE THREAD

**Issue by KbyteTutu** [splunk/vscode-extension-splunk#69]
I set the URL and token then the splunk plugin warned me"Could not enumerate saved searches. self signed certificate in certificate chain".

I checked the closed issue and found that you guys updated a feature about SSL serveral days ago,and I unchecked splunk.commands.enableCertificateVerification.

But it seems that nothing happend, it still required me the warning above.

**Comment by mcauto** [comment]
https://github.com/splunk/vscode-extension-splunk/issues/63

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)
