### ISSUE TITLE
connection_host key issue in inputs.conf

### ISSUE THREAD

**Issue by tdshplunk** [splunk/vscode-extension-splunk#71]
With Splunk Extension version 0.2.10, I receive an `Invalid key in stanza [udp://:11514]: connection_host = dns` in my inputs.conf file. Here is my following stanza:

```
[udp://:11514]
connection_host = dns
host = myhost
index = test
```
<img width="599" alt="vscode_keyerror_inputs" src="https://user-images.githubusercontent.com/105827272/200450576-c0e89b1c-edfa-4ced-b2e7-71f4e3b1485c.png">

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)
