### ISSUE TITLE
forwardedindex.filter.disable key issue in outputs.conf

### ISSUE THREAD

**Issue by tdshplunk** [splunk/vscode-extension-splunk#72]
With Splunk Extension version 0.2.10, I receive an `Invalid key in stanza [tcpout]: forwardedindex.filter.disable = true` in my outputs.conf file. Here is my following stanza:

```
[indexAndForward]
index = false

[tcpout]defaultGroup - indexerClusterPeers
forwardedindex.filter.disable = true
indexAndForward = false

[tcpout:indexerClusterPeers]
server = [10.10.10.10:9997](http://10.10.10.10:9997/)
```

<img width="599" alt="vscode_keyerror_outputs" src="https://user-images.githubusercontent.com/105827272/200450929-b5a2f045-d8df-4708-9f29-ed508036ce47.png">

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)
