### ISSUE TITLE
serverRepositoryLocationPolicy key issue in deploymentclient.conf

### ISSUE THREAD

**Issue by tdshplunk** [splunk/vscode-extension-splunk#73]
With Splunk Extension version 0.2.10, I receive an `Invalid key in stanza [deployment-client]: serverRepositoryLocationPolicy = rejectAlways` in my deploymentclient.conf file. Here is my following stanza:

```
[deployment-client]
phoneHomeIntervalinSecs = 60
repositoryLocation = $SPLUNK_HOME/etc/master-apps
serverRepositoryLocationPolicy = rejectAlways
```

<img width="599" alt="vscode_keyerror_deploymentclients" src="https://user-images.githubusercontent.com/105827272/200451193-3276f846-8b22-4d1a-acbe-67179d3040c1.png">

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)
