### ISSUE TITLE
bucketRebuildMemoryHint key issue in indexes.conf

### ISSUE THREAD

**Issue by tdshplunk** [splunk/vscode-extension-splunk#74]
With Splunk Extension version 0.2.10, I receive an Invalid key in stanza [my_index]: bucketRebuildMemoryHint = 0 in my indexes.conf file. Here is my following stanza:

[stanza]
homePath = volume:primary/stanza/db
bucketRebuildMemoryHint = 0

<img width="348" alt="indexes_conf" src="https://user-images.githubusercontent.com/105827272/202588317-c19a7704-a31c-4db4-8d83-abe2e61a191a.png">

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)
