### ISSUE TITLE
Invalid key: useACK in stanza [tcpout:<target_group>] in outputs.conf

### ISSUE THREAD

**Issue by manjumeti** [splunk/vscode-extension-splunk#75]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/105849352/205225564-76bfe4b1-6bce-41f1-a1cf-06a3bf638ec0.png">

From: https://docs.splunk.com/Documentation/Splunk/9.0.2/Admin/Outputsconf
`useACK = <boolean>`
* Whether or not to use indexer acknowledgment.
* You can configure this setting at the `[tcpout]` or `[tcpout:<target_group>]`
  stanza levels. You cannot set it for individual servers at the
 ` [tcpout-server: ...]` stanza level.

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)
