### ISSUE TITLE
Invalid Key "authType" in stanza [authentication] for authentication.conf file

### ISSUE THREAD

**Issue by TonyBrookILSTU** [splunk/vscode-extension-splunk#84]
Splunk Extension v 0.2.10
File version set to 9.0

Working in `authentication.conf`

For the `[authentication]` stanza, `authType=LDAP` reports as invalid. The popup says "no quick fixes available" 

![image](https://github.com/splunk/vscode-extension-splunk/assets/53791048/b4616e4f-18fa-4c17-a56e-76109e5cf768)

if I go to add the line again, the IntelliSense reports options correctly:
![image](https://github.com/splunk/vscode-extension-splunk/assets/53791048/28bbdffb-c01b-4d26-ab0f-c617a875511a)

It also recommends valid options:
![image](https://github.com/splunk/vscode-extension-splunk/assets/53791048/ffb1eff2-ab1e-44fe-a742-d53774be3a41)

However, no matter what authType I choose, a couple seconds later the linting will report that it is invalid.

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)

**Comment by JasonConger** [comment]
Fixed in version [0.3.0](https://github.com/splunk/vscode-extension-splunk/releases/tag/v0.3.0)
