### ISSUE TITLE
Invalid keys in outputs.conf

### ISSUE THREAD

**Issue by 31337-4554551n** [splunk/vscode-extension-splunk#99]
It looks like the optional configs in the outputs.conf spec aren't being read.

Things like defaultGroup or server highlight fine.

but optional settings like useACK, maxQueueSize, compressed etc are all being labled as invalid.

**Comment by JasonConger** [comment]
Which version of the extension are you using?  `outputs.conf` handling was updated in version 0.3.0.  See #75 for more detail.

**Comment by 31337-4554551n** [comment]
Ah yes.
I updated to 0.3.1 and the issue remains with at least "maxQueueSize"

I should update more often. I'm keeping an eye on the investigation of adding this to the VScodium market place. That's my mistake.

So there are still outputs.conf issues, just not as bad as I originally made it sound.

**Comment by JasonConger** [comment]
Version 0.3.2 addresses the `maxQueueSize` issue.

`phoneHomeIntervalInSec` should be `phoneHomeIntervalInSecs` ("s" at the end).
